### ISSUE TITLE
Unhandled python exception

### ISSUE THREAD

**Issue by m-kuhn** [opengisch/qgis-swiss-locator#37]
When typing "schloh" with QGIS 3.23 I get the following exceptions, only visible on the terminal, nothing popping up on the UI.
This shows up once for a reload of the results in the results list

```
Traceback (most recent call last):
  File "python/plugins/swiss_locator/swiss_locator_filter.py", line 482, in handle_response
    if res['title']['de'] == 'GetMap':
KeyError: 'de'
```

I also have the following in the message panel, not sure if the two are related (this one is only shown once)

```
2022-02-04T11:55:00     WARNING    An error has occurred while executing Python code:
             
             
             swiss_locator.core.network_access_manager.RequestsExceptionUserAbort: Network error: Operation canceled
             
             
             Traceback (most recent call last):
              File "python/plugins/swiss_locator/core/network_access_manager.py", line 329, in replyFinished
              self.request(redirection_url.toString())
              File "python/plugins/swiss_locator/core/network_access_manager.py", line 243, in request
              raise self.http_call_result.exception
             swiss_locator.core.network_access_manager.RequestsExceptionUserAbort: Network error: Operation canceled
             
             
             
             
             Python version: 3.10.2 (main, Jan 17 2022, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
             
             
             QGIS version: 3.23.0-Master Master, 91fe84841d
```

**Comment by m-kuhn** [comment]
I can no longer reproduce
